config/routes.rb
ViddlerApp::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :videos do
    collection do
      get 'recent'
      get 'popular'
      get 'my'
      get 'uploaded'
    end
    member do 
      post 'delete'
    end
    resource :vote, :only => [:create, :destroy]
  end
  
  root :to => 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  belongs_to :session
  has_many :votes, :dependent => :destroy
  has_many :voters, :through => :votes, :source => :session

  validates :video_id, :uniqueness => {:case_sensitive => false}, :presence => true
  validates :title, :presence => true, :length => {:maximum => 140}, :on => :update
  validates_associated :user, :on => :update

  accepts_nested_attributes_for :user

  extend FriendlyId
  friendly_id :video_id, :use => :slugged

  scope :published, where("videos.published_at IS NOT NULL")
  scope :unpublished, where("videos.published_at IS NULL AND videos.user_id IS NOT NULL")
  scope :registered, where("videos.user_id IS NOT NULL")
  scope :recent, order("videos.created_at DESC")
  scope :popular, order("videos.votes_sum DESC")
  scope :my, lambda {|su| su.is_a?(Session) ? where("videos.session_id = ?", su.id) : where("videos.user_id = ?", su.id)}

  after_destroy :delete_on_viddler

  class Viddler
    cattr_accessor :session
    class << self
      
      def authenticate!
        @@session ||= begin
          session = ::Viddler::Client.new(::ViddlerApp::Viddler.api_key)
          session.xauthenticate! ::ViddlerApp::Viddler.user, ::ViddlerApp::Viddler.password, :get_record_token => "1"
          session
        end
      end
      
      def session
        @@session
      end
      
      # [{'id' => "234234e2", 'title' => ...}, ...]
      def videos
        result = @@session.get 'viddler.videos.getByUser', :per_page => 100
        result['list_result']['video_list'] || []
      end
      
      # {"234234e2" => {'id' => "234234e2", 'title' => ...}, ...}
      def hashed_videos
        videos.inject({}) do |h, v|
          h[v['id']] = v
          h
        end
      end
      
    end
  end

  class << self

    def instance_for(attributes = {})
      record = new attributes
      record
    end
    
  end

  def webcam?
    self.source == 'webcam'
  end

  def upload?
    self.source == 'upload'
  end
  
  def delete_on_viddler
    Video::Viddler.authenticate!
    result = Video::Viddler.session.post 'viddler.videos.delete', 
      :sessionid => Video::Viddler.session.sessionid, :video_id => self.video_id
    !!result['success']
  rescue ::Viddler::ApiException
    false
  end
  
  def sync_attributes!
    result = false
    if self.video_id
      result = Video::Viddler.session.get 'viddler.videos.getDetails', :video_id => self.video_id
      self.title ||= result['video']['title']
      self.description ||= result['video']['description']
      self.url ||= result['video']['url']
      self.thumbnail_url ||= result['video']['thumbnail_url']
    end
    result
  end
  
  def published?
    !!self.published_at
  end
  
  def registered?
    !!self.user
  end

  def human_source_name
    webcam? ? I18n.t("videos.recorded_video") : I18n.t("videos.uploaded_video")
  end

  def human_status_name
    if self.published?
      I18n.t("videos.status.published")
    elsif self.registered?
      I18n.t("videos.status.registered")
    else
      I18n.t("videos.status.created")
    end
  end

  def voted?(session)
    self.voters.where("sessions.id" => session.id).count > 0
  end
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  respond_to :html, :js, :json
  before_filter :viddler_authenticate
  before_filter :get_record_token
  before_filter :prepare_upload
  before_filter :find_video, :only => [:show, :edit, :update, :delete]
  before_filter :authentication_required, :only => [:edit, :update]
  before_filter :build_user, :only => [:edit, :update]
  before_filter :build_video, :only => [:new, :index, :create, :uploaded]
  after_filter :update_current_session_with_user, :only => :update
  
  def index
    # nothing to do here
  end

  def create
    @video.sync_attributes!
    @video.save
    respond_with(@video, :layout => !request.xhr?)
  end
  
  def update
    @video.attributes = video_params.merge(:user => @user)
    @video.save and @video.user.save
    respond_with @video
  end
  
  def delete
    @video.destroy
    respond_with @video
  end
  
  # viddler callback after file upload
  def uploaded
    @video.video_id = params[:videoid]
    @video.sync_attributes!
    @video.save
    respond_to do |format|
      format.js
      format.html do
        responds_to_parent do
          render :template => "videos/uploaded.js"
        end
      end
    end
  end
  
  def recent
    @videos = current_session.videos.published.recent
    render :template => "videos/list", :layout => false
  end

  def popular
    @videos = current_session.videos.published.popular
    render :template => "videos/list", :layout => false
  end

  def my
    @videos = current_session.videos.my(current_session)
    render :template => "videos/list", :layout => false
  end
  
  protected
  
  def get_record_token
    @record_token = @viddler.session['record_token']
  end
  
  def find_videos
    @videos = current_session.videos
  end

  def video_params
    @video_params ||= (params[:video] || params[:recorded_video] || params[:uploaded_video] || {}).symbolize_keys
  end

  def build_user
    @user ||= User.new video_params.delete(:user) || {}
  end
  
  def prepare_upload
    upload = @viddler.get 'viddler.videos.prepareUpload'
    @video_upload_url = upload['upload']['endpoint']
    @video_upload_token = upload['upload']['token']
  end
  
  def find_video
    if @video = Video.find_by_video_id(params[:id])
      @user = @video.user
    else
      render :template => "videos/not_found"
      return false
    end
  end
  
  def build_video
    @video = Video.instance_for({:source => "upload", :session => current_session}.merge(video_params.merge(:user => @user)))
  end
  
  def update_current_session_with_user
    if @video && @video.session == current_session && @video.user && @video.user.errors.blank?
      current_session.update_attribute(:user, @video.user)
    end
  end

  def authentication_required
    if @video && (@video.registered? || @video.session != current_session)
      redirect_to video_path(@video), :status => :moved_permanently
    end
  end
  
end

app/helpers/videos_helper.rb
module VideosHelper
  
  def video_upload_url
    @video_upload_url or raise "viddler upload url not available, call prepare_upload."
  end

  def video_upload_token
    @video_upload_token or raise "viddler upload token not available, call prepare_upload."
  end

  def edit_video_link(video = @video)
    %(<a id="#{edit_video_link_dom_id(video)}" data-controls-modal="#{edit_video_dom_id(video)}" data-backdrop="static"></a>).html_safe
  end
  
  def video_dom_id(video = @video)
    "modal-video-#{video.video_id}"
  end
  
  def edit_video_dom_id(video = @video)
    "edit-modal-video-#{video.video_id}"
  end

  def edit_video_link_dom_id(video = @video)
    "edit-modal-video-#{video.video_id}-link"
  end
  
  def delete_video_link(video = @video)
    %(<a href="#{delete_video_path(video.video_id)}" class="btn secondary delete-video" rel="nofollow" data-content="#{video.video_id}">#{t ".delete"}</a>).html_safe
  end

  def vote_video_link(video = @video)
    if video.published?
      text, state = video.voted?(current_session) ? [t(".voted"), "voted"] : [t(".vote"), "active"]
      %(<a href="#" class="btn primary vote-video #{state}" rel="nofollow" data-vote-video-url="#{video_vote_path(video)}" data-video-id="#{video.video_id}">#{text}</a>).html_safe
    end
  end

  def video_status_label(video)
    if video.published?
      "success"
    elsif video.registered?
      "notice"
    else
      "default"
    end
  end
  
end

app/views/videos/_edit.html.erb
<% 
	video  ||= @video
	width  ||= 200
	height ||= 125
	dom_id ||= edit_video_dom_id(video)
%>
<div id="<%= dom_id %>" class="modal hide fade in video-popup">
	<div class="modal-header">
		<a href="#" class="close">×</a>
		<h3><%= t(".title") %></h3>
	</div>
	
	<% content_for :embed do %>
	<p class="embed">
		<%=raw video_embed_code(video.video_id, :player_type => 'simple', :width => width, :heigth => height) %>
		<label><%= video.human_source_name %></label>
	</p>
	<% end %>

	<%= simple_form_for video, :url => video_path(video), 
		:html => {:method => :put, :id => "edit-form", :multipart => true, :class => "edit form-stacked"}, 
			:remote => true, :validate => true do |f| %> 
			
		<%= render "form", :f => f %>
		
		<div class="modal-footer">
			<input type="submit" class="btn primary" value="<%= t ".submit" %>">&nbsp;
			<button type="reset" class="btn cancel"><%= t ".reset" %></button>
			<%= yield :delete %>
		</div>
	<% end %>
</div>

app/views/videos/_form.html.erb
<div class="modal-body">
	<%= yield :embed %>
	<div class="fields">
		<%= f.error_notification %>
			<div class="clearfix string required">
				<%= f.label :title, "<abbr title=\"required\">*</abbr> #{raw t ".title.label"}".html_safe, :class => "string required" %>
				<div class="input">
					<%= f.text_field :title, :class => "large string required", :size => 30, "data-validate" => "true" %>
					<span class="help-block"><%=raw t ".title.hint" %></span>
				</div>
			</div>
			<%= f.fields_for f.object.user || User.new do |u| %>
				<div class="clearfix string required">
					<%= u.label :name, "<abbr title=\"required\">*</abbr> #{raw t ".name.label"}".html_safe, :class => "string required" %>
					<div class="input">
						<%= u.text_field :name, :class => "large string required", :size => 30, "data-validate" => "true" %>
						<span class="help-block"><%=raw t ".name.hint" %></span>
					</div>
				</div>

				<div class="clearfix string required">
					<%= u.label :email, "<abbr title=\"required\">*</abbr> #{raw t ".email.label"}".html_safe, :class => "string required" %>
					<div class="input">
						<%= u.text_field :email, :class => "large string required unique", :size => 30, "data-validate" => "true" %>
						<span class="help-block"><%=raw t ".email.hint" %></span>
					</div>
				</div>
			
				<div class="clearfix">
					<div class="input">
						<ul class="inputs-list">
							<li>
								<label for="user-terms">
									<%= u.check_box :terms, :id => "user-terms" %>
									<span><%=raw t ".terms" %></span>
								</label>
							</li>
						</ul>
					</div>
				</div>
				<div class="clearfix">
					<div class="input">
						<span class="help-block">
							<%=raw t ".notice" %>
						</span>
					</div>	
				</div>
			<% end %>

	</div>
	<div class="clearfix"></div>
</div>

app/views/videos/_new.html.erb
<%
	source ||= "upload"
%>
<% if source == "upload" %>
<div id="modal-uploader" class="modal hide fade in">
	<div class="modal-header">
		<a href="#" class="close">×</a>
		<h3><%= t ".title" %></h3>
	</div>
	<%= form_tag video_upload_url, :id => "upload-form", :multipart => true, "data-validate" => "true",
	    :target => "upload-iframe" do |f| %> 
		<%= hidden_field_tag :uploadtoken, video_upload_token %>
		<%= hidden_field_tag :callback, uploaded_videos_url %>
		<div class="modal-body">
			<p>
				<fieldset>
					<div class="clearfix file required">
						<label for="file"><abbr title="required">*</abbr> <%= t(".file.label").html_safe %></label>
						<div class="input">
							<%= file_field_tag :file, "data-validate" => "true" %>
							<span class="help-block"><%= t(".file.hint").html_safe %></span>
						</div>
					</div>
				</fieldset>	
			</p>
		</div>
		<div class="modal-footer">
			<input type="submit" class="btn primary" value="<%= t ".submit" %>">&nbsp;
			<button type="reset" class="btn cancel"><%= t ".reset" %></button>
		</div>
	<% end %>
	<iframe name="upload-iframe" id="upload-iframe"></iframe>
</div>

<% else %>
<%
	width = 525
	height = 436
	flashvars = "recQuality=M&maxlength=20&fake=1&recordToken=#{@record_token}"
%>
<div id="modal-recorder" class="modal hide fade in">
	<div class="modal-header">
		<a href="#" class="close">×</a>
		<h3><%= t "record.title" %></h3>
	</div>
	<div class="modal-body">
		<p>
			<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"  codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="<%= width %>" height="<%= height %>" id="viddler_recorder" align="middle"> 
				<param name="allowScriptAccess" value="always" /> 
				<param name="allowNetworking" value="all" /> 
				<param name="movie" value="http://cdn-static.viddler.com/flash/recorder.swf" /> 
				<param name="quality" value="high" /> 
				<param name="scale" value="noScale"> 
				<param name="bgcolor" value="#000000" /> 
				<param name="flashvars" value="<%= flashvars %>" /> 
				<embed src="http://cdn-static.viddler.com/flash/recorder.swf" quality="high" scale="noScale" bgcolor="#000000" allowScriptAccess="always" allowNetworking="all" width="<%= width %>" height="<%= height %>" name="viddler_recorder" flashvars="<%= flashvars %>" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
			</object>
		</p>
	</div>
</div>

<% end %>

app/views/videos/_show.html.erb
<% 
	video ||= nil 
	width ||= 525
	height ||= 436
	dom_id ||= video_dom_id(video)
%>
<div id="<%= dom_id %>" data-video-id="<%= video.video_id %>" class="modal hide fade in video-popup">
	<div class="modal-header">
		<a href="#" class="close">×</a>
		<h3><%= video.title || "No Title" %></h3>
	</div>
	<div class="modal-body">
		<p class="embed">
			<%= video_embed_code(video.video_id, :player_type => 'simple', :width => width, :heigth => height) %>
		</p>
	</div>
	<div class="modal-footer">
	  <%= vote_video_link(video) %>
		<div class="twitter-button">
		  <a href="https://twitter.com/share?url=<%= video_url(video) %>&amp;via=<%=u t("site.twitter").strip %>&amp;text=<%=u t("twitter", :title => video.title).strip %>" class="twitter-share-button">Tweet</a>
		</div>
		<div class="facebook-button">
			<fb:like send="false" layout="button_count" width="250" show_faces="false" href="<%= video_url(video) %>"></fb:like>
		</div>
		<%= @delete_button %>
		<% @delete_button = nil %>
	</div>
</div>

app/views/videos/create.js.erb
$(document).trigger("hide-popovers");
<% if @video.errors.any? %>
	$.alert("<%=j error_messages_for(@video) %>", "error");
<% else %>
	<% if @video.upload? %>
		$.alert("<%=j t(:upload_success).html_safe %>", "notice");
		<% flash[:notice] = t(:upload_success).html_safe %>
	<% elsif @video.webcam? %>
		$.alert("<%=j t(:recording_success).html_safe %>", "notice");
		<% flash[:notice] = t(:recording_success).html_safe %>
	<% end %>
	<% if false %>
	$.get("<%= edit_video_path(@video) %>", {}, function() {
		window.eval(data.responseText);
	}, "script");
	<% else %>
		window.location = '<%= edit_video_url(@video) %>';
	<% end %>
<% end %>

app/views/videos/edit.html.erb
<%= render "edit", :video => @video %>
<%= edit_video_link %>
<%= javascript_tag do %>
	$(function() {
		$("#<%= edit_video_link_dom_id %>").trigger("click");
	});
<% end %>

app/views/videos/edit.js.erb
$("#<%= edit_video_dom_id %>").remove();
$("#<%= edit_video_link_dom_id %>").remove();
$("body").append("<%=j render("edit").html_safe %>");
$("body").append("<%=j edit_video_link %>");
$("#<%= edit_video_link_dom_id %>").trigger("click");

app/views/videos/list.html.erb
<% if @videos.blank? %>
	<p>No videos available.</p>
<% else %>
	<% @videos.each do |video| %>
	<li>
		<% if current_session == video.session && !video.user %>
			<% @delete_button = capture do %>
				<%= delete_video_link(video) %>
			<% end %>
			<%
				partial, dom_id = "edit", edit_video_dom_id(video)
			%>
		<% elsif current_session == video.session || (video.user && current_session.user == video.user) %>
			<% @delete_button = capture do %>
				<%= delete_video_link(video) %>
			<% end %>
			<%
				partial, dom_id = "show", video_dom_id(video)
			%>
		<% else %>
			<%
				partial, dom_id = "show", video_dom_id(video)
			%>
		<% end %>
		<%= render partial, :video => video %>
		<a data-controls-modal="<%= dom_id %>" data-backdrop="static" rel="popover" data-content="<%= video.description %><span class='label <%= video_status_label(video) %>'><%= video.human_status_name %></span>" data-original-title="<%= video.title %>" data-video-id="<%= video.video_id %>" class="thumb">
			<%= image_tag video.thumbnail_url, :size => "114x86", :alt => video.title %>
		</a>
	</li>
	<% end %>
	<script>
		$(document).trigger("list-loaded");
	</script>
<% end %>

app/views/videos/new.html.erb
<%= render "new" %>

app/views/videos/not_found.html.erb
<%= javascript_tag do %>
	$.alert('<%=raw t("video_not_found", :id => params['id']) %>', "error");
<% end %>

app/views/videos/show.html.erb
<%= render "show", :video => @video, :dom_id => video_dom_id(@video) %>
<a id="<%= video_dom_id(@video) %>-link" data-controls-modal="<%= video_dom_id(@video) %>" data-backdrop="static" rel="popover" data-content="<%= @video.description %>" data-original-title="<%= @video.title %>">
</a>
<%= javascript_tag do %>
	$(function() {
		$("#<%= video_dom_id(@video) %>-link").trigger("click");
	});
<% end %>

app/views/videos/update.js.erb
<% if @video.errors.any? %>
	$.alert("<%=j error_messages_for(@video, false) %>", "error");
	$("#<%= edit_video_dom_id %>").html("<%=j render('edit').html_safe %>");
<% else %>
	$(document).trigger("hide-popovers");
	$.alert("<%=j t(:update_success).html_safe %>", "notice");
	window.location = '<%= video_url(@video) %>';
<% end %>

app/views/videos/uploaded.js.erb
<% if @video.errors.any? %>
  $.alert("<%= I18n.t(:upload_error).html_safe %>", "error");
  $(top.document).trigger("hide-popovers");
<% else %>
  top.window.location = '<%= edit_video_url(@video) %>'
<% end %>